[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = --strict-markers --tb=short --disable-warnings
testpaths = tests
markers =
    smoke: Mark test as a smoke test
    slow: Mark test as slow running
    integration: Mark test as an integration test
